input = line


ADD = 'add'
ARP = 'arp'
BRIDGE = 'bridge'
CHAIN = 'chain'
HANDLE = 'handle'
IDENTIFIER = /[a-zA-Z][a-zA-Z0-9]{0,63}/
INDEX = 'index'
INET = 'inet'
IP = 'ip'
IP6 = 'ip6'
LAST = 'last'
NETDEV = 'netdev'
POSITION = 'position'
RULE = 'rule'
SEMICOLON = ';'
STRING = '<string>'
TABLE = 'table'
TOKEN_EOF        =  !/./

_NEWLINE = /\m/

# stmt_separator = ';'
identifier = IDENTIFIER | LAST

family_spec_explicit = IP | IP6 | INET | ARP | BRIDGE | NETDEV
family_spec = family_spec_explicit?
table_spec = family_spec identifier
add_cmd = ( TABLE | CHAIN )? table_spec
base_cmd = ADD? add_cmd

line = stmt_separator | add_cmd ( stmt_separator | TOKEN_EOF )


/* converted on Sun Dec 22, 2024, 16:10 (UTC-06) by bison-to-w3c v0.67 which is Copyright (c) 2011-2024 by Gunther Rademacher <grd@gmx.net> */

stmt_separator = _NEWLINE | SEMICOLON

rule_alloc = stmt
stmt     = ( nat_stmt | redir_stmt ) | verdict_stmt
verdict_stmt = VERDICT
nat_stmt = SNAT | DNAT
redir_stmt = REDIRECT